name: 'Publish to chroma.zone'
inputs:
  src-dir:
    default: 'docs'
  dst-dir:
    default: ${{ github.event.repository.name }}
  token:
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Checkout build repo
      uses: actions/checkout@v4
      with:
        repository: 'vanjac/chroma-zone-build'
        path: '_build'
        token: ${{ inputs.token }}
    - name: Relocate build repo
      shell: bash
      run: mv _build ../_build
    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "<>"
    - name: Copy build files
      shell: bash
      run: |
        rsync -a --delete ${{ inputs.src-dir }}/ ../_build/${{ inputs.dst-dir }}
    - name: Commit to build repo
      continue-on-error: true
      shell: bash
      run: |
        cd ../_build
        git add .
        git commit -m "Update ${{ github.event.repository.name }}"
    - name: Push build repo
      shell: bash
      run: |
        cd ../_build
        git push
